import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Providers from "./components/Providers";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MyShop",
  description: "Generated by create next app",
  icons: {
    icon: "/shopping-bag-cart-icon.svg",   // 👉 তোমার লোগো ফাইলের নাম
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Providers>
         <header className="sticky top-0 z-50">
          <Navbar></Navbar>
        </header>
       <main>
         {children}
          <Toaster />
       </main>
       <footer>
        <Footer></Footer>
       </footer>
       </Providers>
      </body>
    </html>
  );
}
